import { Knex } from "knex";
export async function seed(knex: Knex) {
  const tribesSeedData= [
    {"id": 1, "name": "Tech Tribe", "department": "Engineering"},
    {"id": 2, "name": "Marketing Tribe", "department": "Marketing"},
    {"id": 3, "name": "Product Tribe", "department": "Product Management"},
    {"id": 4, "name": "Design Tribe", "department": "Design"},
    {"id": 5, "name": "Sales Tribe", "department": "Sales"},
    {"id": 6, "name": "Data Tribe", "department": "Data Science"},
    {"id": 7, "name": "HR Tribe", "department": "Human Resources"},
    {"id": 8, "name": "Finance Tribe", "department": "Finance"},
    {"id": 9, "name": "Support Tribe", "department": "Customer Support"},
    {"id": 10, "name": "Operations Tribe", "department": "Operations"}
];

  const employeesSeedData = [
    {"name": "Alice Johnson", "title": "Software Engineer", "tribe_id": 1},
    {"name": "Bob Smith", "title": "Product Manager", "tribe_id": 2},
    {"name": "Charlie Brown", "title": "Designer", "tribe_id": 1},
    {"name": "David Wilson", "title": "QA Engineer", "tribe_id": 2},
    {"name": "Eve Davis", "title": "Data Analyst", "tribe_id": 3},
    {"name": "Frank Miller", "title": "DevOps Engineer", "tribe_id": 1},
    {"name": "Grace Lee", "title": "Frontend Developer", "tribe_id": 2},
    {"name": "Hank Garcia", "title": "Backend Developer", "tribe_id": 3},
    {"name": "Ivy Rodriguez", "title": "UX Researcher", "tribe_id": 1},
    {"name": "Jack Martinez", "title": "Systems Architect", "tribe_id": 2},
    {"name": "Karen Hernandez", "title": "Content Strategist", "tribe_id": 3},
    {"name": "Leo Lopez", "title": "Technical Writer", "tribe_id": 1},
    {"name": "Mia Gonzalez", "title": "Sales Manager", "tribe_id": 2},
    {"name": "Nina Wilson", "title": "Marketing Specialist", "tribe_id": 3},
    {"name": "Oscar Perez", "title": "HR Specialist", "tribe_id": 1},
    {"name": "Paula Adams", "title": "Business Analyst", "tribe_id": 2},
    {"name": "Quinn Baker", "title": "Network Engineer", "tribe_id": 3},
    {"name": "Rita Edwards", "title": "Scrum Master", "tribe_id": 1},
    {"name": "Sam Young", "title": "Mobile Developer", "tribe_id": 2},
    {"name": "Tina Kim", "title": "Database Administrator", "tribe_id": 3},
    {"name": "Uma Scott", "title": "IT Support", "tribe_id": 1},
    {"name": "Vera Green", "title": "SEO Specialist", "tribe_id": 2},
    {"name": "Will Baker", "title": "Web Developer", "tribe_id": 3},
    {"name": "Xena Cooper", "title": "Cloud Engineer", "tribe_id": 1},
    {"name": "Yara Reed", "title": "Graphic Designer", "tribe_id": 2},
    {"name": "Zane Bell", "title": "Video Producer", "tribe_id": 3},
    {"name": "Anna Clark", "title": "Copywriter", "tribe_id": 1},
    {"name": "Bradley Wilson", "title": "Market Researcher", "tribe_id": 2},
    {"name": "Cynthia Edwards", "title": "Social Media Manager", "tribe_id": 3},
    {"name": "Derek Stewart", "title": "System Analyst", "tribe_id": 1},
    {"name": "Emma White", "title": "Customer Success Manager", "tribe_id": 2},
    {"name": "Felix Martin", "title": "Compliance Officer", "tribe_id": 3},
    {"name": "Gloria Hall", "title": "Event Coordinator", "tribe_id": 1},
    {"name": "Henry Young", "title": "Procurement Specialist", "tribe_id": 2},
    {"name": "Irene Turner", "title": "Business Development", "tribe_id": 3},
    {"name": "Jackie Allen", "title": "Logistics Coordinator", "tribe_id": 1},
    {"name": "Kyle Walker", "title": "Financial Analyst", "tribe_id": 2},
    {"name": "Laura King", "title": "Risk Manager", "tribe_id": 3},
    {"name": "Mike Wright", "title": "Legal Advisor", "tribe_id": 1},
    {"name": "Nancy Green", "title": "Office Manager", "tribe_id": 2},
    {"name": "Oscar Carter", "title": "Training Coordinator", "tribe_id": 3},
    {"name": "Pamela Scott", "title": "Data Scientist", "tribe_id": 1},
    {"name": "Quincy Lopez", "title": "AI Specialist", "tribe_id": 2},
    {"name": "Rebecca Hill", "title": "E-commerce Manager", "tribe_id": 3},
    {"name": "Steven Adams", "title": "Product Designer", "tribe_id": 1},
    {"name": "Tracy Lewis", "title": "Field Engineer", "tribe_id": 2},
    {"name": "Ulysses Ramirez", "title": "Operations Manager", "tribe_id": 3},
    {"name": "Victoria Murphy", "title": "Pharmaceutical Sales", "tribe_id": 1},
    {"name": "Walter Collins", "title": "Health & Safety Officer", "tribe_id": 2},
    {"name": "Xander Reed", "title": "Quality Control", "tribe_id": 3},
    {"name": "Yvonne Bennett", "title": "Research Analyst", "tribe_id": 1},
    {"name": "Zachary Brooks", "title": "Advertising Manager", "tribe_id": 2},
    {"name": "Allison Foster", "title": "IT Consultant", "tribe_id": 3},
    {"name": "Brandon Sanders", "title": "Content Developer", "tribe_id": 1},
    {"name": "Carmen Cooper", "title": "Customer Support", "tribe_id": 2},
    {"name": "Diana Watson", "title": "Mobile UX Designer", "tribe_id": 3},
    {"name": "Edward Cox", "title": "Cybersecurity Analyst", "tribe_id": 1},
    {"name": "Fiona Diaz", "title": "UX/UI Designer", "tribe_id": 2},
    {"name": "George Powell", "title": "Operations Analyst", "tribe_id": 3},
    {"name": "Helen Sanchez", "title": "Systems Developer", "tribe_id": 1},
    {"name": "Ian Murphy", "title": "Network Administrator", "tribe_id": 2},
    {"name": "Janet Ramirez", "title": "Market Analyst", "tribe_id": 3},
    {"name": "Kevin Torres", "title": "IT Project Manager", "tribe_id": 1},
    {"name": "Lily Griffin", "title": "Product Tester", "tribe_id": 2},
    {"name": "Marcus Hughes", "title": "Creative Director", "tribe_id": 3},
    {"name": "Nora Jenkins", "title": "Digital Marketing", "tribe_id": 1},
    {"name": "Oliver Foster", "title": "Brand Manager", "tribe_id": 2},
    {"name": "Paige Ortiz", "title": "SEO Analyst", "tribe_id": 3},
    {"name": "Quinn Ramirez", "title": "Field Sales Rep", "tribe_id": 1},
    {"name": "Ryan Coleman", "title": "Product Owner", "tribe_id": 2},
    {"name": "Sophie Wong", "title": "User Experience Designer", "tribe_id": 3},
    {"name": "Tyler Simmons", "title": "Data Engineer", "tribe_id": 1},
    {"name": "Ursula Cook", "title": "Artificial Intelligence Engineer", "tribe_id": 2},
    {"name": "Victor Grant", "title": "Blockchain Developer", "tribe_id": 3},
    {"name": "Wendy Adams", "title": "Market Strategist", "tribe_id": 1},
    {"name": "Xena Stone", "title": "Sales Engineer", "tribe_id": 2},
    {"name": "Yasmin Torres", "title": "Graphic Artist", "tribe_id": 3},
    {"name": "Zara Price", "title": "Client Relations Manager", "tribe_id": 1}
];

  await knex("tribes").insert(tribesSeedData);
  await knex("employees").insert(employeesSeedData);
}